{% set name = "jhub-apps" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jhub_apps-{{ version }}.tar.gz
  sha256: bcab358741bbdecd31156ead6142f70da8ab806bb759c6be5e2716cf01ae3a53

build:
  entry_points:
    - japps = jhub_apps.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - hatchling
    - hatch
    - requests
    - fastapi
    - uvicorn
    - jupyterhub
    - jupyter
    - plotlydash-tornado-cmd
    - bokeh-root-cmd
    - jhsingle-native-proxy
    - panel
    - bokeh
    - traitlets
    - pyjwt

test:
  imports:
    - jhub_apps
  commands:
    - pip check
    - japps --help
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/jhub-apps/
  summary: JupyterHub Apps
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
