{% set name = "jhub-apps" %}
{% set version = "2024.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jhub_apps-{{ version }}.tar.gz
  sha256: aea3844fec653cb425ff467088c4d07eb4db8ec4d950b3be259f75f2e30d4ff1

build:
  entry_points:
    - japps = jhub_apps.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - hatchling
    - hatch
    - requests
    - fastapi
    - uvicorn
    - jupyterhub
    - jupyter
    - plotlydash-tornado-cmd
    - bokeh-root-cmd
    - jhsingle-native-proxy
    - panel
    - bokeh
    - traitlets
    - pyjwt
    - python-multipart
    - python-slugify
    - cachetools
    - structlog

test:
  imports:
    - jhub_apps
  commands:
    - pip check
    - japps --help
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/jhub-apps/
  summary: JupyterHub Apps
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
    - dcmcand
    - costrouc
